import { useCallback, useEffect, useMemo, useState } from 'react';
import { useConfiguration } from '@serviceops/confighooks';
import { GenericPanel } from '@serviceops/genericpanel';
import { WorkingDayTemplatesSectionProps } from './WorkingDayTemplatesSection.types';
import {
  DayOfWeek,
  IConfigWorkingDayTemplate,
  IConfigWorkingDayTemplateTime,
} from '@serviceops/interfaces';
import { useStyles } from '../../styles';
import {
  WORKING_DAY_TEMPLATE_CONFIG,
  workingDayTemplateColumns,
} from './WorkingDayTemplatesSection.config';
import { CreateWorkingTimesDialog } from './CreateWorkingTimesDialog';

const toMinutes = (t: string): number | null => {
  const m = /^([0-1][0-9]|2[0-3]):([0-5][0-9])$/.exec(t || '');
  if (!m) return null;
  return Number(m[1]) * 60 + Number(m[2]);
};

const workingHoursFor = (block: IConfigWorkingDayTemplateTime): number => {
  const from = toMinutes(block.fromTime);
  const to = toMinutes(block.toTime);
  if (from === null || to === null || to <= from) return 0;
  return Number(((to - from) / 60).toFixed(2));
};

const WEEKDAYS: DayOfWeek[] = [
  'monday',
  'tuesday',
  'wednesday',
  'thursday',
  'friday',
  'saturday',
  'sunday',
];

interface DayEditContext {
  templateId: string;
  day: DayOfWeek;
  label: string;
  setAllValues: (hoursByDay: Record<string, number>) => void;
}

const WorkingDayTemplatesSection = ({
  data,
  workingTimeRows,
  onDataChange,
  onWorkingTimesChange,
}: WorkingDayTemplatesSectionProps) => {
  const { classes } = useStyles();
  const { calendars: apiCAL, saveSection } = useConfiguration();

  const [workingTimes, setWorkingTimes] = useState<IConfigWorkingDayTemplateTime[]>([]);
  const [dayEditCtx, setDayEditCtx] = useState<DayEditContext | null>(null);

  const rows = data ?? apiCAL?.workingDayTemplates ?? [];
  const workingTimesFinal = workingTimeRows ?? workingTimes;

  useEffect(() => {
    if (workingTimeRows !== undefined) {
      setWorkingTimes(workingTimeRows);
    } else if (apiCAL?.workingDayTemplateTimes) {
      setWorkingTimes(apiCAL.workingDayTemplateTimes);
    }
  }, [workingTimeRows, apiCAL]);

  const handleSave = (next: IConfigWorkingDayTemplate[]) => {
    if (onDataChange) {
      onDataChange(next);
    } else {
      saveSection('calendars', {
        workingDayTemplates: next,
        workingDayTemplateTimes: workingTimesFinal,
        holidayCalendars: apiCAL?.holidayCalendars ?? [],
        bankHolidays: apiCAL?.bankHolidays ?? [],
        workingCalendars: apiCAL?.workingCalendars ?? [],
        workingCalendarTimes: apiCAL?.workingCalendarTimes ?? [],
        composedWorkingTimes: apiCAL?.composedWorkingTimes ?? [],
        calendarWorkLocations: apiCAL?.calendarWorkLocations ?? [],
        calendarConsultants: apiCAL?.calendarConsultants ?? [],
        periodTypes: apiCAL?.periodTypes ?? [],
        timesheetPeriods: apiCAL?.timesheetPeriods ?? [],
        workingShifts: apiCAL?.workingShifts ?? [],
        shiftConsultants: apiCAL?.shiftConsultants ?? [],
      });
    }
  };

  const handleSaveWorkingTimes = (next: IConfigWorkingDayTemplateTime[]) => {
    if (workingTimeRows !== undefined) {
      setWorkingTimes(next);
    }
    if (onWorkingTimesChange) {
      onWorkingTimesChange(next);
    } else {
      saveSection('calendars', {
        workingDayTemplates: rows,
        workingDayTemplateTimes: next,
        holidayCalendars: apiCAL?.holidayCalendars ?? [],
        bankHolidays: apiCAL?.bankHolidays ?? [],
        workingCalendars: apiCAL?.workingCalendars ?? [],
        workingCalendarTimes: apiCAL?.workingCalendarTimes ?? [],
        composedWorkingTimes: apiCAL?.composedWorkingTimes ?? [],
        calendarWorkLocations: apiCAL?.calendarWorkLocations ?? [],
        calendarConsultants: apiCAL?.calendarConsultants ?? [],
        periodTypes: apiCAL?.periodTypes ?? [],
        timesheetPeriods: apiCAL?.timesheetPeriods ?? [],
        workingShifts: apiCAL?.workingShifts ?? [],
        shiftConsultants: apiCAL?.shiftConsultants ?? [],
      });
    }
  };

  // Opened via the pencil icon on a Monday–Sunday field inside the Working
  // Time Template Add/Edit dialog. `rowId` is either the real template id
  // (editing) or a draft id generated by GenericPanel (creating) — either
  // way it's stable for the life of that dialog, so time blocks can be
  // attached to it before the template itself is submitted.
  const handleOpenDayEdit = (params: {
    fieldName: string;
    day: string;
    rowId: string;
    label: string;
    setValue: (hours: number) => void;
    setAllValues: (hoursByDay: Record<string, number>) => void;
  }) => {
    setDayEditCtx({
      templateId: params.rowId,
      day: params.day as DayOfWeek,
      label: params.label,
      setAllValues: params.setAllValues,
    });
  };

  // The template being created/edited may not exist in `rows` yet (still a
  // draft). Inject a placeholder so CreateWorkingTimesPanel's template
  // selector/lookup resolves to it instead of falling back to rows[0].
  const templatesForDayEdit: IConfigWorkingDayTemplate[] = useMemo(() => {
    if (!dayEditCtx) return rows;
    if (rows.some((t) => t.id === dayEditCtx.templateId)) return rows;
    return [
      ...rows,
      {
        id: dayEditCtx.templateId,
        name: 'New working time template',
        shortDescription: '',
        description: '',
        internalNote: '',
        mondayHours: 0,
        tuesdayHours: 0,
        wednesdayHours: 0,
        thursdayHours: 0,
        fridayHours: 0,
        saturdayHours: 0,
        sundayHours: 0,
      },
    ];
  }, [rows, dayEditCtx]);

  const handleSaveWorkingTimesForDayEdit = (next: IConfigWorkingDayTemplateTime[]) => {
    handleSaveWorkingTimes(next);
    if (!dayEditCtx) return;
    // Recompute every day's hours (not just the one being edited) since
    // "Copy day" can write blocks onto other days in the same save.
    const templateBlocks = next.filter((b) => b.workingDayTemplateId === dayEditCtx.templateId);
    const hoursByDay: Record<string, number> = {};
    WEEKDAYS.forEach((day) => {
      const hours = templateBlocks
        .filter((b) => b.dayOfWeek === day)
        .reduce((sum, b) => sum + workingHoursFor(b), 0);
      hoursByDay[day] = Number(hours.toFixed(2));
    });
    dayEditCtx.setAllValues(hoursByDay);
  };

  // Working time template names must be unique — same "already exists"
  // dialog-level Alert pattern used by the Business Category / SLA
  // sections (see BusinessCategoryFormDialog / textUtils.validateSlaRowDuplicate).
  const summaryValidator = useCallback(
    (
      form: Record<string, unknown>,
      _all: unknown[],
      editingRow: Record<string, unknown> | null,
    ): string | null => {
      const nameVal = String(form.name ?? '')
        .trim()
        .toLowerCase();
      if (!nameVal) return null;
      const editingId = (editingRow?.id as string | undefined) ?? null;
      const isDuplicate = rows.some(
        (r) =>
          r.id !== editingId &&
          String(r.name ?? '')
            .trim()
            .toLowerCase() === nameVal,
      );
      return isDuplicate
        ? `Working Time Template "${String(form.name ?? '')}" already exists. Please use a different name.`
        : null;
    },
    [rows],
  );

  return (
    <div className={classes.sectionAccordion}>
      <GenericPanel
        config={WORKING_DAY_TEMPLATE_CONFIG}
        data={rows as any}
        onSave={handleSave}
        customColumns={workingDayTemplateColumns as any}
        variant='plain'
        enableSuccessMessage
        onDayFieldEditClick={handleOpenDayEdit}
        summaryValidator={summaryValidator as unknown as never}
      />

      <CreateWorkingTimesDialog
        open={Boolean(dayEditCtx)}
        onClose={() => setDayEditCtx(null)}
        templates={templatesForDayEdit}
        timeBlocks={workingTimesFinal}
        onSave={handleSaveWorkingTimesForDayEdit}
        templateId={dayEditCtx?.templateId}
        day={dayEditCtx?.day}
      />
    </div>
  );
};

export { WorkingDayTemplatesSection };
