import CommentIcon from '@mui/icons-material/Comment';
import ManageAccountsIcon from '@mui/icons-material/ManageAccounts';
import CheckCircleOutlineIcon from '@mui/icons-material/CheckCircleOutline';
import CancelOutlinedIcon from '@mui/icons-material/CancelOutlined';
import LockOpenIcon from '@mui/icons-material/LockOpen';
import SwapHorizIcon from '@mui/icons-material/SwapHoriz';
import { ReasonCodeTableConfig } from './ReasonCodes.types';

export const REASON_CODE_TABLES: ReasonCodeTableConfig[] = [
  {
    id: 'priority',
    title: 'Priority Change Reason Code',
    subtitle: 'Define reason codes used when changing the priority of a ticket',
    accent: '#0369a1',
    icon: CommentIcon,
    dialogTitle: 'Priority Change Reason Code',
    dialogSubtitle: 'Define a reason code for priority change actions on tickets',
    formLabel: 'Priority Change Code Name',
    formPlaceholder: 'e.g. Business Impact, Escalation Request',
    entityName: 'Priority Change Reason Code',
    dataKey: 'priorityChangeReasonCodes',
    idPrefix: 'prc',
    nameColumnLabel: 'Priority Change Code Name',
    descriptionColumnLabel: 'Description',
    expandedByDefault: true,
  },
  {
    id: 'role',
    title: 'Role Change Reason Code',
    subtitle: 'Define reason codes used when changing the role of a user or assignee',
    accent: '#0369a1',
    icon: ManageAccountsIcon,
    dialogTitle: 'Role Change Reason Code',
    dialogSubtitle: 'Define a reason code for role change actions on users or assignees',
    formLabel: 'Role Change Code Name',
    formPlaceholder: 'e.g. Reassignment, Skill Gap, Workload Balance',
    entityName: 'Role Change Reason Code',
    dataKey: 'roleChangeReasonCodes',
    idPrefix: 'rrc',
    nameColumnLabel: 'Role Change Code Name',
    descriptionColumnLabel: 'Description',
  },
  {
    id: 'resolution',
    title: 'Resolution Code',
    subtitle: 'Define resolution codes used when closing or resolving a ticket',
    accent: '#0369a1',
    icon: CheckCircleOutlineIcon,
    dialogTitle: 'Resolution Code',
    dialogSubtitle: 'Define a resolution code used when closing or resolving tickets',
    formLabel: 'Resolution Code Name',
    formPlaceholder: 'e.g. Fixed, Workaround Applied, Not Reproducible',
    entityName: 'Resolution Code',
    dataKey: 'resolutionCodes',
    idPrefix: 'rc',
    nameColumnLabel: 'Resolution Code Name',
    descriptionColumnLabel: 'Description',
  },
  {
    id: 'cancellation',
    title: 'Cancellation Reason Code',
    subtitle: 'Define reason codes used when cancelling a ticket',
    accent: '#0369a1',
    icon: CancelOutlinedIcon,
    dialogTitle: 'Cancellation Reason Code',
    dialogSubtitle: 'Define a reason code used when cancelling tickets',
    formLabel: 'Cancellation Reason Code Name',
    formPlaceholder: 'e.g. Duplicate, No Longer Needed, Customer Withdrew',
    entityName: 'Cancellation Reason Code',
    dataKey: 'cancellationReasonCodes',
    idPrefix: 'can',
    nameColumnLabel: 'Cancellation Reason Code Name',
    descriptionColumnLabel: 'Description',
  },
  {
    id: 'reopen',
    title: 'Reopen Reason Code',
    subtitle: 'Define reason codes used when reopening a previously closed or resolved ticket',
    accent: '#0369a1',
    icon: LockOpenIcon,
    dialogTitle: 'Reopen Reason Code',
    dialogSubtitle: 'Define a reason code used when reopening closed or resolved tickets',
    formLabel: 'Reopen Reason Code Name',
    formPlaceholder: 'e.g. Issue Recurred, Incomplete Fix, Customer Follow-up',
    entityName: 'Reopen Reason Code',
    dataKey: 'reopenReasonCodes',
    idPrefix: 'rop',
    nameColumnLabel: 'Reopen Reason Code Name',
    descriptionColumnLabel: 'Description',
  },
  {
    id: 'conversion',
    title: 'Conversion Reason Code',
    subtitle: 'Define reason codes used when converting a ticket from one type to another',
    accent: '#0369a1',
    icon: SwapHorizIcon,
    dialogTitle: 'Conversion Reason Code',
    dialogSubtitle: 'Define a reason code used when converting tickets between types',
    formLabel: 'Conversion Reason Code Name',
    formPlaceholder: 'e.g. Misclassified, Scope Change, Customer Request',
    entityName: 'Conversion Reason Code',
    dataKey: 'conversionReasonCodes',
    idPrefix: 'con',
    nameColumnLabel: 'Conversion Reason Code Name',
    descriptionColumnLabel: 'Description',
  },
];
