import { Theme } from '@mui/material/styles';
import { createAppStyles } from '@serviceops/theme';
import { getBaseStyles } from './UserManagement.styles.shared';

export const useStyles = createAppStyles((theme: Theme) => getBaseStyles(theme), {
  admin: {
    container: {},
    title: {},
    description: {},
    tableContainer: {},
    sectionAccordion: {},
    actionToolbar: {},
    toolbarButtons: {},
    tablePaper: {},
    tabsBox: {},
    tabsSearchField: {},
    adminControlsBtn: {},
    adminControlsWrapper: {},
    toolbarSearchField: {},
    selectionIndicator: {},
  },
  user: {
    container: {},
    title: {},
    description: {},
    tableContainer: {},
    sectionAccordion: {},
    actionToolbar: {},
    toolbarButtons: {},
    tablePaper: {},
    tabsBox: {},
    tabsSearchField: {},
    adminControlsBtn: {},
    adminControlsWrapper: {},
    toolbarSearchField: {},
    selectionIndicator: {},
  },
  consultant: {
    container: {},
    title: {},
    description: {},
    tableContainer: {},
    sectionAccordion: {},
    actionToolbar: {},
    toolbarButtons: {},
    tablePaper: {},
    tabsBox: {},
    tabsSearchField: {},
    adminControlsBtn: {},
    adminControlsWrapper: {},
    toolbarSearchField: {},
    selectionIndicator: {},
  },
});
