import { Theme } from '@mui/material/styles';
import { CSSObject } from 'tss-react';

export const getBaseStyles = (theme: Theme): Record<string, CSSObject> => ({
  modal: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: theme.spacing(3),
    pointerEvents: 'none',
    [theme.breakpoints.down('sm')]: {
      justifyContent: 'center',
      alignItems: 'center',
      padding: `${theme.spacing(2)} ${theme.spacing(2)}`,
    },
  },
  card: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing(1.5),
    padding: theme.spacing(1.75, 2.5),
    borderRadius: 12,
    minWidth: 340,
    maxWidth: 480,
    outline: 'none',
    pointerEvents: 'auto',
    backgroundColor: '#ffffff',
    border: '1px solid rgba(0,0,0,0.08)',
    boxShadow: '0 8px 32px rgba(0,0,0,0.12), 0 2px 8px rgba(0,0,0,0.06)',
    position: 'relative' as const,
    overflow: 'hidden' as const,
    [theme.breakpoints.down('sm')]: {
      minWidth: 0,
      width: '100%',
      maxWidth: '100%',
      borderRadius: 10,
      padding: theme.spacing(1.5, 2),
    },
  },
  iconPill: {
    width: 40,
    height: 40,
    minWidth: 40,
    borderRadius: '10px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  icon: {
    fontSize: 22,
  },
  textBlock: {
    display: 'flex',
    flexDirection: 'column',
    gap: theme.spacing(0.25),
    flex: 1,
    minWidth: 0,
  },
  label: {
    fontSize: '0.82rem',
    fontWeight: 700,
    color: '#1f2937',
    letterSpacing: '0.2px',
    lineHeight: 1.2,
  },
  message: {
    fontSize: '0.85rem',
    fontWeight: 400,
    color: '#6b7280',
    lineHeight: 1.5,
  },
  closeBtn: {
    color: '#9ca3af',
    padding: theme.spacing(0.5),
    flexShrink: 0,
    borderRadius: '6px',
    '&:hover': {
      background: 'rgba(0,0,0,0.04)',
      color: '#6b7280',
    },
  },
  accentBar: {
    position: 'absolute' as const,
    left: 0,
    top: 0,
    bottom: 0,
    width: '4px',
  },
});
